spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      routes:
        - id: account_microservice
          uri: http://localhost:8081
          predicates:
            - Path=/accounts/**, /admins/{accountId}, /admins/accounts
          filters:
            - AddResponseHeader=X-Powered-By, Gateway Microservice
        - id: profile_microservice
          uri: http://localhost:8082
          predicates:
            - Path=/profiles/**, /posts/**, /alerts/**, /admins/profiles/**, /admins/alerts/**
          filters:
            - AddResponseHeader=X-Powered-By, Gateway Microservice
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true