spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      routes:
        - id: account_microservice
          uri: http://localhost:8081
          predicates:
            - Path=/accounts/**
        - id: profile_microservice
          uri: http://localhost:8082
          predicates:
            - Path=/profiles/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true